include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Vultus
Vultus_FILES = $(wildcard *.xm) $(wildcard *.x) $(wildcard *.m)
Vultus_CFLAGS = -fobjc-arc
Vultus_FRAMEWORKS = UIKit
Vultus_EXTRA_FRAMEWORKS = Cephei Vultus

include $(THEOS_MAKE_PATH)/tweak.mk
