include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Vultus
Vultus_FILES = Switch.m
Vultus_FRAMEWORKS = UIKit
Vultus_LIBRARIES = flipswitch
Vultus_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
