include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = Vultus
Vultus_FILES = $(wildcard *.m)
Vultus_CFLAGS = -fobjc-arc
Vultus_FRAMEWORKS = AVFoundation CoreGraphics CoreMedia CoreVideo UIKit QuartzCore
Vultus_EXTRA_FRAMEWORKS = opencv2

include $(THEOS_MAKE_PATH)/framework.mk
